from __future__ import annotations

from typing import Any, Protocol


class BrokerExecutionAdapter(Protocol):
    def active_orders(self) -> list[dict[str, Any]]: ...
    def history_orders(self, start_ts: float, end_ts: float) -> list[dict[str, Any]]: ...
    def history_deals(self, start_ts: float, end_ts: float) -> list[dict[str, Any]]: ...
    def order_calc_profit(self, order_type: int, symbol: str, volume: float, price_open: float, price_close: float) -> float | None: ...
    def order_calc_margin(self, order_type: int, symbol: str, volume: float, price: float) -> float | None: ...
    def order_check(self, request: dict[str, Any]) -> dict[str, Any] | None: ...
    def order_send(self, request: dict[str, Any]) -> dict[str, Any] | None: ...
    def update_protection(self, request: dict[str, Any]) -> dict[str, Any] | None: ...
    def cancel_order(self, request: dict[str, Any]) -> dict[str, Any] | None: ...
    def close_position(self, request: dict[str, Any]) -> dict[str, Any] | None: ...
